app/models.py
from typing import Optional
import sqlalchemy as sa
import sqlalchemy.orm as so
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class Collector(UserMixin, db.Model):
    id: so.Mapped[int] = so.mapped_column(sa.Integer, primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(50), nullable=False, unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))
    token: so.Mapped[str] = so.mapped_column(sa.String(256), nullable=False)
    messages: so.WriteOnlyMapped['Message'] = so.relationship(back_populates='collector', passive_deletes=True)

    def __repr__(self):
        return '<Collector {}>'.format(self.name)
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

@login.user_loader
def load_user(id):
    return Collector.query.get(int(id))

class Message(db.Model):
    id: so.Mapped[int] = so.mapped_column(sa.Integer, primary_key=True)
    received_at: so.Mapped[sa.DateTime] = so.mapped_column(sa.DateTime, server_default=sa.func.now())
    received_from: so.Mapped[str] = so.mapped_column(sa.String(50), nullable=False)
    content: so.Mapped[str] = so.mapped_column(sa.Text, nullable=True)
    collector_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey('collector.id'), nullable=False)
    collector: so.Mapped[Collector] = so.relationship(back_populates='messages', passive_deletes=True)

    def __repr__(self):
        return '<Message {}>'.format(self.id)
    
    def remove_old_messages(days=7):
        from datetime import datetime, timedelta
        threshold_date = datetime.now() - timedelta(days=days)
        old_messages = Message.query.filter(Message.received_at < threshold_date).all()
        for message in old_messages:
            db.session.delete(message)
        db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
import sqlalchemy as sa
from app import db
from app.models import Collector

class LoginForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

app/__init__.py
from os import getenv
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_apscheduler import APScheduler


if getenv('SENTRY_DSN'):
    import sentry_sdk
    sentry_sdk.init(
        dsn=getenv('SENTRY_DSN'),
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
    )

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'main.index'
login.login_message = 'Please log in to access this page.'
scheduler = APScheduler()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.subdomain_matching = True

    # Add APScheduler configuration
    app.config['SCHEDULER_API_ENABLED'] = False
    app.config['SCHEDULER_TIMEZONE'] = 'UTC'

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    scheduler.init_app(app)
    
    # Only start the scheduler if we're not in testing mode
    if not app.config.get('TESTING', False):
        scheduler.start()
        # Register scheduled tasks
        with app.app_context():
            from app.tasks import init_scheduler
            init_scheduler()

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.collector import bp as collector_bp
    app.register_blueprint(collector_bp)

    return app

from app import models

app/collector/__init__.py
from flask import Blueprint

bp = Blueprint('collector', __name__)

from app.collector import routes

app/collector/routes.py
from flask import request, jsonify
from app.collector import bp
import sqlalchemy as sa
from app import db
from app.models import Collector, Message

@bp.route('/services/collector', methods=['POST'], subdomain='<sub>')
def collector(sub):
    user = db.session.scalar(sa.select(Collector).where(Collector.name == sub))
    if user is None:
       return {"text": "Incorrect index", "code": 7}, 400

    if not request.authorization:
        return {"text": "Token is required", "code": 2}, 401
    
    auth = str(request.authorization).lstrip("Splunk ")

    if auth != user.token:
        return {"text": "invalid token", "code": 4}, 401
    
    if request.headers.get('X-Real-IP'):
        addr = request.headers.get('X-Real-IP')
    else:
        addr = request.remote_addr

    msg = Message(
        received_from=addr,
        collector=user
    )
    if request.headers.get('Content-Type') == "application/json":
      if request.data == b'':
        print("Empty request")
        msg.content = None
      else:
        msg.content = request.get_data(as_text=True)
    db.session.add(msg)
    db.session.commit()
    return {"text": "Success", "code": 0}


#@bp.route('/services/collector/event', methods=['POST'])
#def collector_json():
#    print(request.json)
#    return jsonify('{"text": "Success", "code": 0}')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import jsonify, request, flash, redirect, url_for, render_template
from flask_login import current_user, login_user, logout_user, login_required
import sqlalchemy as sa
from app import db
from app.models import Collector, Message
from app.main.forms import LoginForm
from uuid import uuid4
from app.main import bp

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
  if current_user.is_authenticated:
    return redirect(url_for('main.view_collector'))

  form = LoginForm()
  if form.validate_on_submit():
    user = db.session.scalar(
      sa.select(Collector).where(Collector.name == form.name.data))

    if user is None:
      collector = Collector(name=form.name.data, token=str(uuid4()))
      collector.set_password(form.password.data)
      db.session.add(collector)
      db.session.commit()
      flash("Collector created")
      login_user(collector)
      return redirect(url_for('main.view_collector'))
    elif user is not None:
      if not user.check_password(form.password.data):
        print('Invalid password')
        flash("Invalid password")
        return redirect(url_for('main.index'))

    login_user(user, remember=form.remember_me.data)
    return redirect(url_for('main.index'))
    
  return render_template('index.html', title='Home', form=form)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@bp.route('/collector', methods=['GET'])
@login_required
def view_collector():
   query = sa.select(Message).order_by(Message.received_at.desc())
   messages = db.session.scalars(query).all()
   return render_template('view_collector.html', messages=messages)

@bp.route('/regenerate', methods=['GET'])
def regenerate():
    if current_user.is_authenticated:
        collector = db.session.scalar(
            sa.select(Collector).where(Collector.name == current_user.name))
        collector.token = str(uuid4())
        db.session.commit()
        flash("Token regenerated")
    else:
        flash("You need to be logged in to do this")
    return redirect(url_for('main.view_collector'))

@bp.route('/delete', methods=['GET'])
def delete():
    if current_user.is_authenticated:
        collector = db.session.scalar(
            sa.select(Collector).where(Collector.name == current_user.name))
        messages = db.session.scalars(
            sa.select(Message).where(Message.collector_id == collector.id)).all()
        for message in messages:
            db.session.delete(message)
        db.session.commit()
        db.session.delete(collector)
        db.session.commit()
        flash("Collector deleted")
    else:
        flash("You need to be logged in to do this")
    return redirect(url_for('main.index'))

app/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
    <title>{{title }} - FakeHEC</title>
    {% else %}
    <title>FakeHEC</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
  </head>
  <body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="container mt-3">
      <div class="alert alert-info" role="alert">
        {% for message in messages %}
        {{ message }}<br />
        {% endfor %}
      </div>
    </div>
    {% endif %}
    {% endwith %}
    <div class="container mt-4">
      {% block head %}{% endblock %}
    </div>
    <div class="mx-auto p-5">
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block head %}
<h1>Welcome to FakeHEC!</h1>
<p>FakeHEC is a simple service emulating the Splunk HTTP Event Collector allowing you to quickly setup and debug a collector for your application.</p>
<p>FakeHEC was developed by <a href="https://github.com/dviske">dviske</a> and the source code is available at <a href="https://github.com/dviske/fakehec">https://github.com/dviske/fakehec</a>.</p>
<hr />
<h3>Getting started</h3>
<p>To get started, please create a collector. A collector has a password associated with it so it cannot be seen by others (though should by no means store sensitive information in FakeHEC) and you will be given a token to pass to your application.</p>
<p>You can use this form both to create and to sign into your collector.</p>
<form class="row row-cols-lg-auto g-3 align-items-center" action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div class="col-12">
        <div class="input-group">
            {{ form.name(class="form-control", placeholder="Name") }}
        </div>
    </div>
    <div class="col-12">
        <div class="input-group">
            {{ form.password(class="form-control", placeholder="Password") }}
        </div>
    </div>
    <div class="col-12">
        <div class="form-check">
            {{ form.remember_me(class="form-check-input") }}
            {{ form.remember_me.label(class="form-check-label") }}
        </div>
    </div>
    <div class="col-12">
        <div class="input-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </div>
</form>
<hr />
<p>FakeHEC is provided for free in good faith. Any attempts at abuse will be met with deletion and IP restrictions.</p>
{% endblock %}

app/templates/view_collector.html
{% extends "base.html" %}

{% block head %}
<h1>FakeHEC - {{ current_user.name }}</h1>
<p>To use your FakeHEC endpoint, point your application to the following details:</p>
<p><b>Host:</b> <code>{{ current_user.name }}.fakehec.dviske.com</code></p>
<p><b>Token:</b> <code>{{ current_user.token }}</code></p>
<a href="{{ url_for('main.regenerate') }}" class="btn btn-primary">Regenerate Token</a>
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmModal">
    Delete Collector
</button>
<br />
<p><a href="{{ url_for('main.logout') }}">Click here to log out</a>.</p>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteConfirmModal" tabindex="-1" aria-labelledby="deleteConfirmModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmModalLabel">Confirm Deletion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this collector? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a href="{{ url_for('main.delete') }}" class="btn btn-danger">Delete Collector</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th scope="col">Received From</th>
            <th scope="col">Received At</th>
            <th scope="col">Content</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for message in messages %}
        <tr>
            <td>{{ message['received_from'] }}</td>
            <td>{{ message['received_at'] }}</td>
            <td>
                {% if message['content'] is none %}
                    <i>This message contained no content.</i>
                {% else %}
                    <code class="text-wrap">{{ message['content'][:100] }}{% if message['content']|length > 100 %}...{% endif %}</code>
                {% endif %}
            </td>
            <td>
                {% if message['content'] is not none and message['content']|length > 100 %}
                    <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#contentModal{{ loop.index }}">
                        Show Full Content
                    </button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Modals for full content -->
{% for message in messages %}
{% if message['content'] is not none and message['content']|length > 100 %}
<div class="modal fade" id="contentModal{{ loop.index }}" tabindex="-1" aria-labelledby="contentModalLabel{{ loop.index }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="contentModalLabel{{ loop.index }}">Full Content from {{ message['received_from'] }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <code class="text-wrap">{{ message['content'] }}</code>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}